# Generated by Django 4.1.1 on 2022-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20191115_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_morrisons',
            new_name='total_amazon',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='total_sainsburys',
            new_name='total_bigbasket',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='total_tesco',
            new_name='total_dmart',
        ),
        migrations.AddField(
            model_name='basket',
            name='total_flipkart',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
