# Generated by Django 4.1.1 on 2022-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191114_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_morrisons',
            new_name='price_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_sainsburys',
            new_name='price_bigbasket',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_tesco',
            new_name='price_dmart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_morrisons',
            new_name='url_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_sainsburys',
            new_name='url_bigbasket',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_tesco',
            new_name='url_dmart',
        ),
        migrations.AddField(
            model_name='product',
            name='price_flipkart',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url_flipkart',
            field=models.CharField(db_index=True, default=None, max_length=250),
        ),
    ]
