# Generated by Django 4.1.1 on 2022-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_price_amazon_product_price_morrisons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
