# Generated by Django 4.1.1 on 2022-11-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_price_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_local',
        ),
    ]
